/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bs_frame_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9309fabbaa5dd88eefb97749c6c1523c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/backscatter/bs_frame_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <bs_frame_decoder_pydoc.h>

void bind_bs_frame_decoder(py::module& m)
{

    using bs_frame_decoder = gr::backscatter::bs_frame_decoder;


    py::class_<bs_frame_decoder,
               gr::block,
               gr::basic_block,
               std::shared_ptr<bs_frame_decoder>>(
        m, "bs_frame_decoder", D(bs_frame_decoder))

        .def(py::init(&bs_frame_decoder::make),
             py::arg("threshold"),
             py::arg("pdu_max_len"),
             D(bs_frame_decoder, make))


        ;
}
