/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(burst_frame_tagger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f3c17177432fcd01e7f14cf541c50fa9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/backscatter/burst_frame_tagger.h>
// pydoc.h is automatically generated in the build directory
#include <burst_frame_tagger_pydoc.h>

void bind_burst_frame_tagger(py::module& m)
{

    using burst_frame_tagger = gr::backscatter::burst_frame_tagger;


    py::class_<burst_frame_tagger,
               gr::block,
               gr::basic_block,
               std::shared_ptr<burst_frame_tagger>>(
        m, "burst_frame_tagger", D(burst_frame_tagger))

        .def(py::init(&burst_frame_tagger::make),
             py::arg("snr_threshoud"),
             py::arg("look_ahead"),
             D(burst_frame_tagger, make))

        .def("set_snr_threshoud",
             &burst_frame_tagger::set_snr_threshoud,
             py::arg("snr_threshoud"),
             D(burst_frame_tagger, set_snr_threshoud))

        ;
}
