/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_rate.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c5e3e7bd4f55e417b398ab4d3d5af394)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/backscatter/pdu_rate.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_rate_pydoc.h>

void bind_pdu_rate(py::module& m)
{

    using pdu_rate = gr::backscatter::pdu_rate;


    py::class_<pdu_rate, gr::block, gr::basic_block, std::shared_ptr<pdu_rate>>(
        m, "pdu_rate", D(pdu_rate))

        .def(py::init(&pdu_rate::make), py::arg("update_rate_ms"), D(pdu_rate, make))


        ;
}
