/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_ber.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d1c3b7ae261ba6c7380b941f71068694)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/backscatter/pdu_ber.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_ber_pydoc.h>

void bind_pdu_ber(py::module& m)
{

    using pdu_ber = gr::backscatter::pdu_ber;


    py::class_<pdu_ber, gr::block, gr::basic_block, std::shared_ptr<pdu_ber>>(
        m, "pdu_ber", D(pdu_ber))

        .def(py::init(&pdu_ber::make), py::arg("payload"), D(pdu_ber, make))


        ;
}
